### PR TITLE
Add exporter for histogram viewer

### PR DESCRIPTION
**Pull request by Carifio24**
This is the next installment in the series of updates from @victoriaono and myself. This PR adds an exporter for the histogram viewer. The main things I think are worth mentioning:

* Plotly has its own histogram trace, but its binning can differ from glue's, and it doesn't support binning logarithmically (see issue 1844 in the plotly repository). The solution that I landed on is to use Plotly's bar traces rather than a histogram. This allows us to use the heavy lifting that we've already done in glue, by using the layer state's `histogram` property. This directly gives us the positions and heights of the bars in our chart.
* For plots with a log x-axis, this means that the width of each bar is different (in axis units, not visually). AFAICT Plotly's bar trace doesn't support setting a different width for each bar. To work around this, when the x-axis is log we create a separate bar trace for each bin, with an appropriate width, and group them into the same legend group.
* For axis labels, I've taken the position that when glue is using minor ticks, we explicitly set the tick values and text in Plotly. An example of this would be on log axes where the range is smaller than the distance between successive ticks.

### CODE REVIEW

**Review by astrofrog — APPROVED** [review]
Great addition, thanks! I'll look into doing a release shortly with all these new PRs merged :)

**Comment by astrofrog** [comment]
@Carifio24 - can you rebase to resolve the conflict?

**Comment by Carifio24** [comment]
@astrofrog I've just rebased. I removed the changelog commit as well, since I see we've just added the auto-changelog functionality here as well.

**Comment by dhomeier** [comment]
Thanks! For the auto-change log, could you edit the PR title so it reflects what had been pushed in the changelog commit (one-liner will still do, in general)?

**Comment by Carifio24** [comment]
@dhomeier I think this title should be better

**Pull request merged**
