### PR TITLE
Adding support for Histograms.

### PR DESCRIPTION
**Pull request by DumbMachine**
This pull request adds the following features:

- [X] Histogram plot.ly html exporter.
- [X] Histogram2d plot.ly html exporter. 
~~Histogram2dContour plot.ly html exporter~~

### CODE REVIEW

**Comment by DumbMachine** [comment]
@astrofrog I wanted to ask two things:
+ Histogram's layout has the following options ['stack', 'group', 'overlay', 'relative']. How would you want this to be integrated?
+ Plotting a Histogram2dContour is the same as plotting the Hisotgram2d, the only change being the api call. Hisotgram2d changes to Hisotgram2dContour. Should this be included in Hisotgram2d.py itself or another file?

**Comment by astrofrog** [comment]
@DumbMachine - sorry for the delay in reviewing this! I think for now we should just pick the histogram layout option that looks the most similar to what glue does already in the GUI - so I think that's overlay.

Maybe let's leave out the 2D contour option for now, since glue doesn't actually support that yet (for now I think it makes sense to just try and reproduce plots that can be made inside glue).

If you are familiar with rebasing, could you rebase this branch on the latest master branch? (ignore this  if not)

**Comment by DumbMachine** [comment]
@astrofrog - I will make the necessary changes by tomorrow.

**Comment by astrofrog** [comment]
@DumbMachine - thanks!

**Comment by DumbMachine** [comment]
I made a little to many commits, I could squash them if you like. Also, could you take a look at [histogram2d.py](https://github.com/glue-viz/glue-plotly/blob/c23ca613840f414439a57b4f3ddaafa9ffc7a3dc/glue_plotly/html_exporters/histogram2d.py), I removed markers and other options which are not viable for 2d histograms.

**Comment by astrofrog** [comment]
@DumbMachine - thanks for updating the PR! Could you indeed squash the commits and I can then merge this :)

**Comment by DumbMachine** [comment]
Not sure what I did here, I squashed all commits and force push them to the origin. Do not remember closing the issue. ( Sorry for the delay, had forgotten about this )

**Comment by astrofrog** [comment]
Very strange, not sure why it closed - can you try opening a new pull request?

**Pull request closed without merging**
