### PR TITLE
Adding support for Histograms ( Extension of the old one )

### PR DESCRIPTION
**Pull request by DumbMachine**
@astrofrog , Sorry for the delay and mishaps before, now I have forked the repo again and made the same old changes.

### CODE REVIEW

**Comment by astrofrog** [comment]
Huh what is this bot?!

**Comment by pllim** [comment]
"Pull app will automatically watch and pull in upstream's default (master) branch to yours with hard reset." Ouch.

**Comment by astrofrog** [comment]
I never installed it though...

**Comment by pllim** [comment]
It could be that the author installed it in their own fork? 🤷‍♀

**Comment by DumbMachine** [comment]
I'm sorry I was just checking out some GitHub Services. I wasn't really sure about what I was doing. I have uninstalled it now.

**Comment by pllim** [comment]
Unfortunately, this PR is no more. If you have a copy of the content of this PR somewhere on your machine, please push it to a new branch (that is not `master`) and open a new PR from it. Hope this helps!

**Pull request closed without merging**
